application: multiplicationmaster
version: 1
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "300d 5h"

handlers:
- url: /manifest.webapp
  static_files: manifest/manifest.json
  upload: manifest/manifest.json
  http_headers:
    Content-Type: application/x-web-app-manifest+json
- url: /*
  static_dir: static
  http_headers:
    Vary: Accept-Encoding
- url: /*
  static_dir: transient
  http_headers:
    Vary: Accept-Encoding
  expiration: "0d 1h"
- url: /gameon/*
  static_dir: gameon/static
  http_headers:
    Vary: Accept-Encoding
- url: /gameon/*
  script: gameon.gameon.app
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"

instance_class: F2
automatic_scaling:
  max_pending_latency: 7.5s
# automatic_scaling:
#   min_idle_instances: 2
#   max_pending_latency: 4.5s

pagespeed:

  url_blacklist:
  - http://www.multiplicationmaster.com/music/*
  - http://www.multiplicationmaster.com/sitemap
  - http://www.multiplicationmaster.com/manifest.webapp
  - https://multiplicationmaster.appspot.com/buy
  # enabled_rewriters:
  # - CollapseWhitespace
  # - CombineHeads
  # - ElideAttributes
  # - RemoveComments
  # - MinifyCss
  # - InlineJs
  # - LeftTrimUrls

inbound_services:
- warmup
