application: multiplicationmaster
version: 1
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "300d 5h"

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /channel.html
  static_files: channel.html
  upload: channel.html
  expiration: "300d"
- url: /manifest.webapp
  static_files: manifest/manifest.json
  upload: manifest/manifest.json
  http_headers:
    Content-Type: application/x-web-app-manifest+json
# - url: /(.*)html
  # static_files: \1html
  # upload: \1html
- url: /BingSiteAuth.xml
  static_files: BingSiteAuth.xml
  upload: BingSiteAuth.xml
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
  expiration: "0d 1h"
- url: /achievement-hard.html
  static_files: achievement-hard.html
  upload: achievement-hard.html
  expiration: "0d 1h"
- url: /achievement-medium.html
  static_files: achievement-medium.html
  upload: achievement-medium.html
  expiration: "0d 1h"
- url: /gameon/*
  static_dir: gameon/static
  http_headers:
    Vary: Accept-Encoding
- url: /gameon/*
  script: gameon.gameon.app
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"

instance_class: F2
automatic_scaling:
  max_pending_latency: 7.5s
# automatic_scaling:
#   min_idle_instances: 2
#   max_pending_latency: 4.5s

pagespeed:

  url_blacklist:
  - /music/*
  - /sitemap
  - /manifest.webapp
  - /buy
  # enabled_rewriters:
  # - CollapseWhitespace
  # - CombineHeads
  # - ElideAttributes
  # - RemoveComments
  # - MinifyCss
  # - InlineJs
  # - LeftTrimUrls

inbound_services:
- warmup
